// Regenerates src/assets/fonts.generated.ts — base64 data-URI modules for the
// bundled, subsetted variable fonts. Run after re-subsetting the woff2 sources
// in src/assets/ (see build/fonts/subset.py for the subsetting recipe):
//   node scripts/generate-fonts.mjs
//
// We embed the fonts as data URIs in a generated .ts (not via an esbuild
// loader) so EVERY bundler that pulls in themeRegistry — the main build and
// both acceptance harnesses — picks them up with zero loader config.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const assets = join(root, "src", "assets");

function dataUri(file) {
  const b64 = readFileSync(join(assets, file)).toString("base64");
  return `data:font/woff2;base64,${b64}`;
}

const pretendard = dataUri("pretendard-subset.woff2");
const jbmono = dataUri("jbmono-subset.woff2");

const out = `// AUTO-GENERATED by scripts/generate-fonts.mjs — DO NOT EDIT BY HAND.
// Subsetted variable fonts (Pretendard Variable + JetBrains Mono) inlined as
// base64 woff2 data URIs so the plugin renders the correct typeface offline,
// on the first frame, with measurement-pinned metrics (no CDN dependency).
// Pretendard: OFL 1.1 (orioncactus/pretendard). JetBrains Mono: OFL 1.1.
/* eslint-disable */
export const PRETENDARD_WOFF2_DATAURL = ${JSON.stringify(pretendard)};
export const JETBRAINS_MONO_WOFF2_DATAURL = ${JSON.stringify(jbmono)};
`;

const target = join(assets, "fonts.generated.ts");
writeFileSync(target, out);
console.log(
  `Wrote ${target}\n  Pretendard data URI: ${pretendard.length} chars\n  JetBrains Mono data URI: ${jbmono.length} chars`
);
